// Every UI string. German first; an English table follows the same shape.

import { type CardState, type ConfigProblemCode, type DemoSettingsProblem, type ErrorCode, EXPORT_HTML_MAX, type NarrationLanguage, type VoiceKind, type Idea, type Need, type NextStep, type Queue, type OwnerHold, type RestartReason } from '../core/types';

export const t = {
  kind: { task: 'Aufgabe', project: 'Projekt', workstream: 'Workstream', idea: 'Idee', prototype: 'Prototyp', becomesProject: 'Idee → Projekt' },
  state: {
    idea: 'Idee',
    proposal: 'Vorschlag eines Agenten',
    planned: 'Geplant',
    working: 'Agent arbeitet',
    waiting: 'Wartet auf dich',
    approved: 'Freigegeben',
    inPr: 'Im PR',
    live: 'Live',
    done: 'Erledigt',
  } satisfies Record<CardState, string>,
  need: { demo: 'Demo bereit', question: 'Frage an dich', review: 'Bereit zur Abnahme' } satisfies Record<Need, string>,
  demoWithQuestion: 'Demo bereit, mit Frage',
  finishing: 'Live · Agent erledigt den Rest',
  finishingLong: 'Auf main. Der Agent erledigt noch, was nach dem Landen ansteht; danach endet seine Sitzung.',
  finishingDone: 'Erledigt · Agent räumt auf',
  finishingDoneLong: 'Ohne Änderung am Code gibt es nichts zu landen. Der Agent erledigt noch, was ansteht; danach endet seine Sitzung.',
  proposalMark: '✦ Vorschlag',
  progress: (live: number, all: number) => `${live} von ${all} live`,
  needsYou: 'brauchen dich',
  newCard: 'Neue Aufgabe',
  keys: 'Ziehen: verschieben · ⌘ + Scrollen / Pinch: Zoom · 0: Übersicht · Doppelklick: neue Aufgabe · K: Koordinator · A: Archiv · Leertaste halten: sprechen',
  close: 'Schließen (Esc)',
  sheetGrip: 'Breite ziehen · Doppelklick: zurück auf die Standardbreite',
  planSheet: 'Projekt · Plan',
  plan: {
    read: 'Plandokument lesen',
    readAt: 'Im Plandokument lesen',
    back: 'Workstreams',
    loading: 'Plandokument wird geladen …',
    failed: 'Das Plandokument ließ sich nicht laden.',
    startAll: (n: number) => (n === 1 ? 'Den geplanten Workstream starten' : `Alle ${n} Workstreams starten`),
    startAllShort: (n: number) => (n === 1 ? '1 starten' : `Alle ${n} starten`),
    startTakenBack: 'Start zurückgenommen; die Workstreams sind wieder geplant.',
    startAllHint: 'Der Koordinator plant sie gemeinsam: Was unabhängig ist, startet sofort; was auf einen anderen aufbaut oder mit ihm kollidiert, wartet auf ihn.',
    startedAll: (n: number) => (n === 1 ? 'Workstream beim Koordinator.' : `${n} Workstreams beim Koordinator; er legt die Reihenfolge fest.`),
  },
  archivedProject: 'Projekt · Archiv',
  fromIdea: 'Entstanden aus der Idee',
  decisions: 'Entscheidungen',
  noDecisions: 'Noch keine Entscheidungen.',
  decidedBy: { owner: 'du', project: 'Projekt-Agent für dich', koordinator: 'Koordinator für dich' },
  fromPlan: 'Aus dem Plan-Dokument; geändert wird es dort:',
  titlePlaceholder: 'Worum geht es?',
  bodyPlaceholder: 'Beschreibung',
  delete: 'Löschen',
  deleted: (title: string) => `„${title}“ gelöscht.`,
  undo: 'Rückgängig',
  offline: 'Keine Verbindung zum Server',
  noCanvas: 'Obeya hat keine Leinwand. Beim Start ein Repository angeben.',
  repos: (n: number) => `${n} Repositories`,
  switchCanvas: 'Leinwand wechseln',
  waitingThere: (n: number) => (n === 1 ? '1 Aufgabe braucht dich dort' : `${n} Aufgaben brauchen dich dort`),
  waitingElsewhere: (n: number) => (n === 1 ? '1 Aufgabe auf einer anderen Leinwand braucht dich' : `${n} Aufgaben auf anderen Leinwänden brauchen dich`),
  start: 'Agent starten',
  stop: 'Anhalten',
  approve: 'Freigeben',
  approveNoChange: 'Beenden',
  noChangeHint: 'Keine Änderung am Code: Beenden schließt die Karte ab, ohne Pull Request.',
  accept: 'Übernehmen und starten',
  acceptOnly: 'Übernehmen',
  dismiss: 'Verwerfen',
  send: 'Senden',
  compose: {
    working: 'Hinweis an den Agenten – er arbeitet weiter',
    question: 'Eigene Antwort',
    review: 'Feedback – der Agent arbeitet daran weiter',
  },
  questionFromWorker: 'Frage des Agenten',
  ask: {
    question: 'Frage an dich',
    questions: 'Fragen an dich',
    several: 'Mehrere möglich',
    words: 'Eigene Antwort oder Anmerkung – optional',
    send: 'Antworten',
    /** On the option the asking agent would pick itself. */
    pick: 'Würde ich nehmen',
    pickWhy: (why: string) => `Der Agent würde so entscheiden: ${why}`,
  },
  summary: 'Zusammenfassung des Agenten',
  proposal: 'Vorschlag',
  proposedBy: (title: string) => `Vorgeschlagen vom Agenten der Aufgabe „${title}“.`,
  followUpOf: (title: string) => `Kommt von der Aufgabe „${title}“.`,
  task: 'Auftrag',
  log: 'Verlauf',
  logEmpty: 'Noch nichts passiert.',
  lastFailure: (at: string) => `Zuletzt gescheitert (${at})`,
  author: { worker: 'Agent', owner: 'Du', project: 'Projekt-Agent', koordinator: 'Koordinator', obeya: 'Obeya', explorer: 'Explorations-Agent' },
  branch: 'Branch',
  started: (title: string) => `Agent arbeitet an „${title}“.`,
  answered: 'Antwort ist beim Agenten.',
  approved: 'Freigegeben.',
  approvedNoChange: 'Beendet.',
  accepted: 'Vorschlag übernommen und gestartet.',
  dismissed: 'Vorschlag verworfen.',
  stopped: 'Agent angehalten.',
  queue: {
    checking: 'Koordinator prüft',
    cutting: 'Koordinator teilt auf',
    cuttingLong: 'Der Koordinator schneidet die Aufgabe in Pakete, die parallel laufen können. Sie ersetzen die Aufgabe.',
    waiting: 'In der Warteschlange',
    checkingLong: 'Der Koordinator prüft, ob die Aufgabe mit laufender Arbeit wahrscheinlich in Merge-Konflikte gerät.',
    behind: (titles: string[]) => `Wartet auf ${titles.map((x) => `„${x}“`).join(', ')}.`,
    force: 'Trotzdem starten',
    dequeue: 'Aus der Warteschlange nehmen',
    forced: 'Gestartet, trotz möglicher Merge-Konflikte.',
    dequeued: 'Aus der Warteschlange genommen.',
  },
  /** Tags on the cards around the one the pointer is on: it waits for them, or they wait for it. */
  deps: {
    before: 'kommt zuerst',
    after: 'wartet darauf',
  },
  /** Why the server refused an action; `invalid` is also the text for anything unknown. */
  error: {
    unknownCard: 'Das gibt es nicht mehr.',
    project: 'Ein Projekt wird über seine Workstreams bearbeitet, nicht als Ganzes.',
    notPlanned: 'Nur eine geplante Aufgabe kann gestartet werden.',
    queued: 'Die Aufgabe liegt schon beim Koordinator.',
    notQueued: 'Die Aufgabe wartet nicht in der Warteschlange.',
    notSplittable: 'Aufteilen lässt sich nur eine eigene, geplante Aufgabe, die nicht beim Koordinator liegt.',
    noAgent: 'An dieser Aufgabe arbeitet gerade kein Agent.',
    noQuestion: 'Hier ist keine Frage mehr offen.',
    notReady: 'Das ist nicht bereit zur Abnahme.',
    notProposal: 'Das ist kein Vorschlag mehr.',
    planCard: 'Das kommt aus dem Plan-Dokument; geändert wird es dort.',
    noWorkspace: 'Kein Workspace frei: Alle sind belegt oder es ist keiner eingerichtet.',
    dirtyWorkspaces: 'Kein Workspace frei: Jeder freie hat noch nicht committete Änderungen.',
    workspace: 'Der Workspace für den Agenten ließ sich nicht vorbereiten (git-Fehler).',
    emptyText: 'Bitte zuerst einen Text eingeben.',
    unknownPreference: 'Diese Präferenz gibt es nicht mehr.',
    imageType: 'Das ist kein Bild, das der Agent lesen kann (PNG, JPEG, GIF oder WebP).',
    imageTooLarge: 'Das Bild ist zu groß, auch verkleinert.',
    notDone: 'Archivieren lässt sich nur eine eigene Aufgabe, die live oder erledigt ist, oder eine verworfene Idee.',
    notArchived: 'Das liegt nicht mehr im Archiv.',
    notIdea: 'Das ist keine Idee (mehr).',
    ideaThinking: 'Der Agent arbeitet noch an seiner Antwort. Bauen oder Planen geht, sobald sie da ist.',
    prototypeRunning: 'Für diese Idee liegt noch ein Prototyp auf der Leinwand.',
    notPrototype: 'Das ist kein Prototyp (mehr).',
    prototypeEnded: 'Ein verworfener oder gebauter Prototyp bleibt im Archiv. Für einen neuen Versuch: an der Idee einen neuen Prototyp bauen lassen.',
    nothingToStart: 'Alle Workstreams laufen schon oder liegen beim Koordinator.',
    noShare: 'Teilen lässt sich nur eine Video-Demo, und nur in einem Repository, das Demos teilt.',
    shareBusy: 'Die Seite wird gerade geteilt oder zurückgezogen.',
    notShared: 'Die Demo ist nicht geteilt.',
    exportTooLarge: 'Das Video ist zu groß für eine einzelne HTML-Datei; als ZIP geht es.',
    landDirty: 'Nicht gelandet: Im Workspace liegen noch nicht committete Änderungen. Der Agent kümmert sich darum; danach landet die Arbeit ohne neue Freigabe.',
    landConflict: 'Nicht gelandet: Beim Rebase auf main gab es Konflikte. Der Agent löst sie; danach landet die Arbeit ohne neue Freigabe.',
    landEmpty: 'Nicht gelandet: Der Branch enthält keine Commits. Der Agent sieht nach; danach landet die Arbeit ohne neue Freigabe.',
    landCheckout: 'Nicht gelandet: Der Obeya-Checkout steht nicht auf main. Bitte dort auf main wechseln und erneut freigeben.',
    landMerge: 'Nicht gelandet: Der Obeya-Checkout hat lokale Änderungen an denselben Dateien. Bitte dort committen oder beiseitelegen und erneut freigeben.',
    land: 'Nicht gelandet: git-Fehler im Obeya-Checkout.',
    config: 'Nicht gespeichert: Die Konfiguration hat Fehler.',
    voiceSample: 'Die Probe ließ sich nicht erzeugen:',
    voiceInstalling: 'Es wird schon eine Stimme installiert.',
    invalid: 'Das hat nicht geklappt. Der Server hat die Aktion abgelehnt.',
  } satisfies Record<ErrorCode, string>,
  offlineError: 'Der Server ist nicht erreichbar.',
  scope: 'Voraussichtlich betroffen',
  voice: {
    hold: 'Halten zum Sprechen (Leertaste)',
    koordinator: 'Koordinator',
    card: (title: string) => `Koordinator · Aufgabe: ${title}`,
    idea: (title: string) => `Koordinator · Idee: ${title}`,
    project: (title: string) => `Koordinator · Projekt: ${title}`,
    noMic: 'Kein Mikrofon: der Browser hat den Zugriff nicht erlaubt.',
    notReady: 'Das Mikrofon war noch nicht bereit; bitte noch einmal.',
    flat: 'Das Mikrofon liefert keinen Ton.',
    failed: 'Das hat nicht geklappt; bitte noch einmal.',
    typePlaceholder: 'Dem Koordinator schreiben, z. B. „Neue Aufgabe: …“',
    tooLate: 'Zu spät: das ist schon passiert.',
    attach: 'Screenshot für die nächste Sprachnachricht – oder mit ⌘V einfügen oder auf das Mikrofon ziehen',
  },
  pr: {
    title: (n: number) => `Pull Request #${n}`,
    conflict: 'Konflikt mit dem Zielbranch; der Agent bringt den Branch auf Stand.',
    ready: 'Bereit zum Mergen: Checks grün, alle Anmerkungen erledigt, das Review ist durch. Mergen auf GitHub.',
    noChecks: 'Noch keine Checks.',
    opening: 'Der Agent öffnet den Pull Request.',
    review: 'Review',
    round: (n: number, author: string) => `Runde ${n} · ${author}`,
    threads: (n: number, open: number) =>
      `${n === 1 ? '1 Anmerkung' : `${n} Anmerkungen`}, ${open === 0 ? (n === 1 ? 'erledigt' : 'alle erledigt') : `${open} offen`}`,
    replies: (n: number) => (n === 1 ? '1 Antwort' : `${n} Antworten`),
    resolved: 'Erledigt',
    open: 'Offen',
    agent: 'Agent',
    onGithub: 'Auf GitHub',
    edited: (time: string) => `${time} überarbeitet`,
    short: (n: number, failed: number, conflict: boolean, ready?: boolean) =>
      [`PR #${n}`, failed ? `${failed} ${failed === 1 ? 'Check rot' : 'Checks rot'}` : '', conflict ? 'Konflikt' : '', ready ? 'Bereit zum Mergen' : ''].filter(Boolean).join(' · '),
  },
  demo: { question: 'Offene Frage', answerPlaceholder: 'Antwort an den Agenten', yourAnswer: 'Deine Antwort', shown: 'Gezeigt', notShown: 'Nicht gezeigt', findings: 'Auffälligkeiten', none: '–', kept: 'Die Demo bleibt hier abrufbar.',
    artifact: 'HTML-Artefakt des Agenten',
    noDemo: 'Ohne Demo',
    followUp: 'Als Aufgabe anlegen',
    followedUp: (title: string) => `Aufgabe „${title}“ angelegt`,
  },
  share: {
    share: 'Teilen',
    shareHint: 'Veröffentlicht das Video auf einer Seite für die Kollegen, mit dem Befehl zum Teilen dieses Repositorys',
    exportHint: 'Die Demo als Datei zum Weitergeben herunterladen',
    exportIntro: 'Für dieses Repository ist kein Ziel zum Teilen eingerichtet (Konfiguration). Die Demo lässt sich als Seite herunterladen und weitergeben.',
    zip: 'Als ZIP',
    zipHint: 'Ein Ordner mit der Seite (index.html) und dem Video daneben',
    html: 'Als HTML-Datei',
    htmlHint: 'Eine einzige Datei mit Seite und Video, zum Verschicken',
    tooLarge: (bytes: number) => `Für eine einzelne Datei ist das Video zu groß (${(bytes / 1024 / 1024).toFixed(1)} MB, höchstens ${EXPORT_HTML_MAX / 1024 / 1024} MB).`,
    preparing: 'Wird vorbereitet …',
    writingPage: 'Der Text der Seite wird zuerst geschrieben; das dauert etwas.',
    again: 'Neu teilen',
    againHint: 'Die geteilte Seite bekommt die neue Demo; der Link bleibt.',
    stop: 'Nicht mehr teilen',
    stopHint: 'Nimmt die Seite herunter; erneutes Teilen bringt sie unter demselben Link zurück.',
    open: 'Öffnen',
    copy: 'Link kopieren',
    copied: 'Link kopiert.',
    shared: 'Geteilt',
    publishing: 'Wird veröffentlicht …',
    withdrawing: 'Wird zurückgezogen …',
    stale: 'Die geteilte Seite zeigt noch die frühere Demo.',
    outdated: 'Seiten werden inzwischen anders erzeugt; diese zeigt noch die frühere Fassung.',
    reshare: 'Erneut teilen',
    reshareHint: 'Erzeugt die Seite neu, mit derselben Demo; der Link bleibt.',
  },
  koordinator: {
    button: 'Koordinator',
    kind: 'Koordinator',
    title: 'Planung und Präferenzen',
    queue: 'Warteschlange',
    queueEmpty: 'Nichts wartet.',
    running: 'In Arbeit',
    runningEmpty: 'Gerade arbeitet kein Agent.',
    proposals: 'Vorschläge',
    proposalsHint:
      'Der Koordinator hat sie aus deinen Worten gelernt. Sie gelten erst, wenn du sie übernimmst. Regeln für eine CLAUDE.md sammelt die Aufgabe „CLAUDE.md ergänzen“; sie startet, sobald kein Vorschlag mehr offen ist.',
    proposalsCount: (n: number) => (n === 1 ? 'Ein Vorschlag für eine Regel' : `${n} Vorschläge für Regeln`),
    target: 'Gehört in',
    targetPreferences: 'Deine Präferenzen',
    targetClaudeMd: (repo: string) => `CLAUDE.md von ${repo}`,
    queuedCount: (n: number) => (n === 1 ? 'Eine Aufgabe in der Warteschlange' : `${n} Aufgaben in der Warteschlange`),
    fromReview: 'Aus der Rückschau',
    changes: (rule: string) => `Ändert „${rule}“`,
    accept: 'Übernehmen',
    change: 'Ändern',
    reject: 'Verwerfen',
    cancel: 'Abbrechen',
    preferences: 'Deine Präferenzen',
    preferencesHint:
      'Wie die Agenten über Obeya mit dir arbeiten, in jedem Repo. Alle Agenten halten sich daran. Was du hier einträgst oder dem Koordinator mit „Merk dir: …“ sagst, gilt sofort; was ein Repo betrifft, kommt in dessen Aufgabe „CLAUDE.md ergänzen“.',
    edit: 'Zum Bearbeiten klicken',
    remove: 'Entfernen',
    add: 'Hinzufügen',
    addPlaceholder: 'Neue Regel',
    filed: (repo: string) => `In die Aufgabe „CLAUDE.md ergänzen“ für ${repo} aufgenommen.`,
    undone: 'zurückgenommen',
    lookingUp: 'schlägt nach …',
  },
  config: {
    button: 'Konfiguration',
    kind: 'Obeya',
    title: 'Konfiguration',
    fromFile: 'Gespeichert in',
    fromArgs: (file: string) =>
      `Obeya läuft gerade mit den Repositories von der Kommandozeile. Speichern legt ${file} an; Obeya startet dann daraus, auch künftig, wenn es ohne Repositories gestartet wird.`,
    koordinator: 'Der Koordinator kennt sie auch: frag ihn danach oder sag ihm, was sich ändern soll.',
    canvas: (n: number) => `Leinwand ${n}`,
    name: 'Name',
    nameAuto: (name: string) => `automatisch: ${name}`,
    runs: 'läuft',
    fresh: 'neu',
    freshHint: 'Neue Kennung: Obeya zeigt hier eine neue, leere Leinwand.',
    gone: (names: string) => `Nicht mehr dabei: ${names}. Ihre Aufgaben und Projekte bleiben gespeichert und kommen mit der Leinwand zurück.`,
    path: 'Pfad zum Repository',
    home: 'Heimat',
    adapter: 'Adapter',
    adapterAuto: (picked?: string) => (picked ? `automatisch (${picked})` : 'automatisch'),
    worktrees: 'Agenten arbeiten in Worktrees',
    clonesMode: 'Agenten arbeiten in Klonen',
    clones: 'Klone anlegen',
    workspaces: 'Vorhandene Klone, einer pro Zeile',
    share: 'Befehl zum Teilen von Demos',
    shareAdapter: (adapter: string) => `leer: der des Adapters ${adapter}`,
    shareNone: 'leer: Teilen exportiert eine Datei',
    shareHint:
      'Wird im Repository ausgeführt: mit „publish“ und der Seite als JSON auf stdin, gibt die URL der Seite aus; „withdraw <slug>“ nimmt sie herunter. Ein Skript (.ts, .js) läuft mit Obeyas Bun.',
    addRepo: '+ Repository',
    removeRepo: 'Repository entfernen',
    addCanvas: '+ Leinwand',
    removeCanvas: 'Leinwand entfernen',
    server: 'Server (von der Kommandozeile)',
    port: 'Port',
    dataDir: 'Daten',
    permissionMode: 'Rechte der Agenten',
    restarts: 'Startet bei neuem Code neu',
    yes: 'ja',
    no: 'nein (--dev)',
    save: 'Speichern und neu starten',
    saveOnly: 'Speichern',
    reset: 'Verwerfen',
    saved: 'Gespeichert. Obeya startet neu, sobald kein Agent mitten in einem Schritt ist; die Seite lädt dann von selbst neu.',
    savedOnly: 'Gespeichert. Gilt ab dem nächsten Start von Obeya.',
    json: 'Als JSON',
    loading: 'Konfiguration wird geladen …',
    problem: {
      noCanvas: 'Obeya braucht mindestens eine Leinwand.',
      noRepo: 'Eine Leinwand braucht mindestens ein Repository.',
      notRepo: 'Unter diesem Pfad liegt kein git-Repository.',
      unknownAdapter: 'Diesen Adapter gibt es nicht.',
      sameId: 'Gleiche Kennung wie eine andere Leinwand: bitte einen anderen Namen geben.',
      homeMissing: 'Das Repository, mit dem die Leinwand angelegt wurde, fehlt; es muss dabeibleiben.',
      notClone: 'Ein Klon in der Liste ist kein git-Repository.',
      shareCommand: 'Das Programm des Befehls zum Teilen gibt es nicht.',
      invalid: 'Die Konfiguration ist fehlerhaft.',
    } satisfies Record<ConfigProblemCode, string>,
    demo: {
      title: 'Demos',
      hint: 'Wie Agenten ihre Demos vertonen. Gilt ab der nächsten Aufnahme, ohne Neustart.',
      language: 'Sprache der Erzählung',
      languages: { de: 'Deutsch', en: 'Englisch' } satisfies Record<NarrationLanguage, string>,
      voice: 'Stimme',
      groups: { local: 'Auf diesem Rechner', service: 'Dienst (API-Schlüssel)', own: 'Eigene' },
      voices: {
        piper: 'Piper (Standard)',
        qwen3: 'Qwen3-TTS (bessere Qualität)',
        say: 'macOS „say“',
        gemini: 'Gemini',
        openai: 'OpenAI',
        elevenlabs: 'ElevenLabs',
        azure: 'Azure',
        command: 'Eigener Befehl',
        http: 'Eigener HTTP-Dienst',
      } satisfies Record<VoiceKind, string>,
      about: {
        piper: 'Läuft auf jedem Rechner, schnell auch ohne Grafikkarte. Obeya installiert Piper und die Stimme auf Wunsch.',
        qwen3: 'Natürlicher als Piper, braucht aber viel Speicher; auf einem Mac mit MLX, sonst praktisch nur mit Grafikkarte. Mit einer Stimmprobe klont es eine Stimme.',
        say: 'Kostenlos und sofort da, klingt aber deutlich synthetischer.',
        gemini: 'Googles Gemini TTS. Die kostenlose Stufe erlaubt nur wenige Anfragen am Tag.',
        openai: 'OpenAIs Sprachausgabe, oder ein Dienst mit derselben Schnittstelle unter eigener Adresse.',
        elevenlabs: 'ElevenLabs, auch mit einer dort geklonten Stimme (deren Voice-ID).',
        azure: 'Microsofts Azure Speech, mit einer Neural-Stimme.',
        command: 'Ein Programm auf diesem Rechner: bekommt den Text auf stdin und schreibt die WAV-Datei nach $DEMO_WAV.',
        http: 'Ein eigener Dienst: bekommt per POST {"text", "language"} als JSON und antwortet mit Audio.',
      } satisfies Record<VoiceKind, string>,
      field: {
        voiceName: (v: VoiceKind) => (v === 'qwen3' ? 'Sprecher' : v === 'elevenlabs' ? 'Voice-ID' : 'Name der Stimme'),
        reference: () => 'Stimmprobe zum Klonen (.wav, das genaue Transkript als .txt daneben)',
        command: () => 'Befehl',
        url: (v: VoiceKind) => (v === 'azure' ? 'Region (z. B. westeurope) oder Adresse' : v === 'openai' ? 'Adresse' : 'Adresse des Dienstes'),
        keyFile: (v: VoiceKind) => `Datei mit dem API-Schlüssel${v === 'http' ? ' (optional, als Bearer-Token)' : ''}`,
      },
      placeholder: {
        voiceName: () => 'leer: Standardstimme',
        reference: () => 'leer: ein fester Sprecher',
        command: () => 'z. B. uv run --project ~/stimme python sprich.py',
        url: (v: VoiceKind) => (v === 'openai' ? 'leer: api.openai.com' : v === 'azure' ? 'westeurope' : 'https://…'),
        keyFile: (v: VoiceKind) =>
          `leer: aus ${({ gemini: 'GEMINI_API_KEY', openai: 'OPENAI_API_KEY', elevenlabs: 'ELEVENLABS_API_KEY', azure: 'AZURE_SPEECH_KEY' } as Partial<Record<VoiceKind, string>>)[v] ?? 'DEMO_TTS_API_KEY'}`,
      },
      ownVoice: 'Das ist meine eigene Stimme',
      person: { first: 'Erzählt in der Ich-Form, weil es deine eigene Stimme ist.', third: 'Erzählt ohne „ich“: Die Stimme ist nicht deine.' },
      notInstalled: (what: string, size: string) => `Noch nicht installiert: ${what} (etwa ${size}).`,
      install: (size: string) => `Installieren (${size})`,
      installing: 'Wird installiert …',
      installFailed: (why: string) => `Installation fehlgeschlagen: ${why}`,
      listen: 'Anhören',
      sampling: 'Erzeuge Probe …',
      listenBack: 'Erzählung mit Whisper gegenhören (findet verschluckte Wörter; ohne bleibt sie ungeprüft)',
      save: 'Demo-Einstellungen speichern',
      saved: 'Gespeichert. Die nächste Demo nutzt sie.',
      problem: {
        noCommand: 'Für den eigenen Befehl fehlt der Befehl.',
        noUrl: 'Es fehlt die Adresse (bei Azure die Region).',
        noKey: 'Es fehlt der API-Schlüssel: eine Datei, oder die Umgebungsvariable des Dienstes.',
        keyFileMissing: 'Die Datei mit dem API-Schlüssel gibt es nicht.',
        referenceMissing: 'Die Stimmprobe gibt es nicht.',
        noTranscript: 'Neben der Stimmprobe fehlt ihr Transkript (gleicher Name, .txt).',
        notHere: '„say“ gibt es nur auf einem Mac.',
      } satisfies Record<DemoSettingsProblem, string>,
    },
  },
  restart: {
    pill: (n: number, owner: OwnerHold[]) => {
      const agents = n === 1 ? '1 Agenten' : `${n} Agenten`;
      const you = owner.length === 2 ? 'dein Video und Diktat' : owner[0] === 'video' ? 'dein Video' : 'dein Diktat';
      return `Neustart wartet auf ${!owner.length ? agents : n ? `${agents} und ${you}` : you}`;
    },
    until: (time: string) => `spätestens ${time}`,
    reason: {
      code: 'Auf main liegt neuer Code, mit dem Obeya neu startet.',
      config: 'Die Konfiguration wurde gespeichert; Obeya startet mit ihr neu.',
    } satisfies Record<RestartReason, string>,
    waits: 'Die Agenten wissen Bescheid und pausieren beim nächsten sicheren Punkt. Obeya wartet noch auf:',
    elsewhere: (n: number) => (n === 1 ? '1 Agent auf einer anderen Leinwand' : `${n} Agenten auf anderen Leinwänden`),
    owner: {
      video: 'Du siehst ein Demo-Video: Obeya startet neu, sobald du es anhältst oder es zu Ende ist.',
      voice: 'Du diktierst: Obeya startet neu, sobald dein Diktat verarbeitet ist und nicht mehr zurückgenommen werden kann.',
    } satisfies Record<OwnerHold, string>,
    kept: 'Was du offen hast, ist nach dem Neustart wieder offen, an derselben Stelle.',
    deadline: (time: string) => `Um ${time} startet Obeya auf jeden Fall neu.`,
    deadlineOwner: (time: string) => `Um ${time} startet Obeya neu, auch wenn Agenten noch arbeiten, aber nicht mitten in deinem Video oder Diktat.`,
    now: 'Jetzt neu starten',
    nowRisk:
      'Ohne zu warten: Die Agenten werden mitten im Schritt unterbrochen. Was sie gerade laufen lassen (Tests, Builds, gestartete Server, eine Demo-Aufnahme), wird gestoppt. Nach dem Neustart machen sie in ihrer Sitzung weiter und erfahren davon, müssen Abgebrochenes aber neu anstoßen; eine halb fertige Änderung liegt bis dahin unfertig im Workspace.',
    nowOwner: 'Ohne zu warten: Dein Video oder Diktat wird unterbrochen. Was offen war, ist danach wieder offen, das Video an derselben Stelle.',
    going: 'Obeya startet neu …',
  },
  archive: {
    button: 'Archiv',
    kind: 'Archiv',
    title: 'Erledigte Aufgaben, Projekte, verworfene Ideen und Prototypen',
    hint: 'Zuletzt archivierte oben. Ein Klick öffnet den Eintrag.',
    empty: 'Noch nichts archiviert.',
    archive: 'Archivieren',
    archiveDone: (n: number) => (n === 1 ? '1 erledigte Aufgabe archivieren' : `${n} erledigte Aufgaben archivieren`),
    unarchive: 'Zurück auf die Leinwand',
    archived: (title: string) => `„${title}“ archiviert.`,
    archivedMany: (n: number) => (n === 1 ? '1 Aufgabe archiviert.' : `${n} Aufgaben archiviert.`),
    unarchived: (title: string) => `„${title}“ ist zurück auf der Leinwand.`,
    /** The heading over the cards archived on one day. */
    day: (d: Date, today = new Date()) => {
      const days = Math.round((startOfDay(today) - startOfDay(d)) / 86_400_000);
      if (days === 0) return 'Heute';
      if (days === 1) return 'Gestern';
      return d.toLocaleDateString('de-DE', { weekday: 'long', day: 'numeric', month: 'long', ...(d.getFullYear() === today.getFullYear() ? {} : { year: 'numeric' }) });
    },
    /** When an archived card went into the archive, on the unfolded card. */
    when: (d: Date) => {
      const day = t.archive.day(d);
      return `archiviert ${day === 'Heute' || day === 'Gestern' ? day.toLowerCase() : `am ${day}`}, ${d.toLocaleTimeString('de-DE', { hour: '2-digit', minute: '2-digit' })}`;
    },
    /** On the archive's timeline, beside a card: when it went into the archive that day. */
    time: (d: Date) => d.toLocaleTimeString('de-DE', { hour: '2-digit', minute: '2-digit' }),
    /** Over an archived project: its plan doc is gone, and the sheet shows it as it last stood. */
    projectGone: (d: Date) => `Das Plan-Dokument ist weg (${t.archive.when(d)}). So stand es zuletzt; kommt die Datei zurück, kehrt das Projekt an seinen Platz zurück.`,
    workstreams: (n: number) => (n === 1 ? '1 Workstream' : `${n} Workstreams`),
  },
  split: 'Aufteilen',
  idea: {
    status: { open: 'Idee', parked: 'Idee · geparkt', dropped: 'Idee · verworfen' } satisfies Record<Idea['status'], string>,
    yourTurn: 'Idee · du bist dran',
    brief: 'Stand der Idee',
    briefEmpty: 'Noch leer. Der Explorations-Agent hält hier fest, was das Gespräch ergibt: Ziel, Varianten, Entscheidungen, offene Fragen.',
    seed: 'Ausgangspunkt',
    talk: 'Gespräch',
    talkEmpty: 'Erzähl, worum es geht. Der Explorations-Agent liest Code und Pläne mit, fragt nach und zeigt Varianten.',
    thinking: 'denkt nach …',
    steps: (n: number) => `Verlauf: ${n} ${n === 1 ? 'Schritt' : 'Schritte'}`,
    compose: 'Frag nach, widersprich, entscheide – oder halte die Leertaste',
    build: 'So bauen',
    planDoc: 'Als Projekt planen',
    prototype: 'Prototyp bauen lassen',
    prototypePlaceholder: 'Der Ansatz in ein paar Worten, dann was der Prototyp zeigen soll. Leer: die Idee, wie sie steht.',
    prototypeGo: 'Prototyp starten',
    park: 'Parken',
    drop: 'Verwerfen',
    waitForReply: 'Antwort kommt gleich: Bauen und Planen gehen, sobald sie da ist.',
    built: 'Die Idee wird gebaut; der Stand der Idee ist ihr Auftrag.',
    planned: 'Ein Agent schreibt jetzt das Plan-Doc; danach steht hier das Projekt.',
    parked: 'Idee geparkt.',
    dropped: 'Idee verworfen. Sie bleibt mit ihrem Stand liegen, bis du sie archivierst.',
    prototyped: 'Ein Agent baut einen Wegwerf-Prototyp.',
    prototypeDemo: 'Prototyp',
    prototypes: 'Prototypen',
    prototypeKept: 'Ein Prototyp landet nie selbst. Überzeugt einer, wird die Idee auf seinem Branch gebaut.',
    prototypeNoDemo: 'Noch keine Demo.',
    reopen: 'Wer weiterredet, nimmt die Idee wieder auf.',
    makeIdea: 'Erst besprechen',
    /** What the idea's agent would do next in the owner's place, above the decisions; the button it means is marked. */
    next: 'Nächster Schritt, wenn der Agent entscheiden müsste',
    nextStep: {
      answer: (n: number) => (n > 1 ? 'Erst die Fragen beantworten' : 'Erst die Frage beantworten'),
      build: () => 'So bauen',
      planDoc: () => 'Als Projekt planen',
      prototype: () => 'Prototyp bauen lassen',
      park: () => 'Parken',
      drop: () => 'Verwerfen',
    } satisfies Record<NextStep['step'], (questions: number) => string>,
    /** The same, short, on the canvas card of an idea that waits for the owner. */
    suggests: {
      answer: 'Tipp: erst antworten',
      build: 'Tipp: so bauen',
      planDoc: 'Tipp: als Projekt',
      prototype: 'Tipp: Prototyp',
      park: 'Tipp: parken',
      drop: 'Tipp: verwerfen',
    } satisfies Record<NextStep['step'], string>,
    prototypeOf: (title: string) => `Wegwerf-Prototyp für die Idee „${title}“. Er landet nie selbst: Verwerfen legt ihn ins Archiv, „Diesen Prototyp bauen“ baut die Idee auf seinem Branch.`,
    discard: 'Verwerfen',
    discarded: 'Prototyp verworfen; er liegt mit seiner Demo im Archiv.',
    buildPrototype: 'Diesen Prototyp bauen',
    builtPrototype: (idea: string) => `Die Idee „${idea}“ wird auf diesem Prototyp gebaut; ihre anderen Prototypen sind verworfen.`,
    buildProposal: 'Der Agent schlägt vor, die Idee auf diesem Prototyp zu bauen',
    acceptBuild: 'Annehmen: so bauen',
    /** On the canvas card of a prototype whose worker proposes building the idea on it. */
    proposesBuild: 'Vorschlag: so bauen',
    /** An archived prototype, how it ended. */
    ended: { discarded: 'Prototyp · verworfen', built: 'Prototyp · gebaut' },
    endedLong: {
      discarded: (idea: string) => `Verworfener Prototyp der Idee „${idea}“. Sein Code ist weg; Demo, Zusammenfassung und Log bleiben hier. Ein neuer Versuch ist ein neuer Prototyp.`,
      built: (idea: string) => `Gebaut als Idee „${idea}“: Die Idee wird auf dem Branch dieses Prototyps gebaut.`,
    },
    builtOn: (title: string) => `Gebaut auf dem Prototyp „${title}“; sein Branch ist der dieser Aufgabe.`,
  },
  shots: {
    attach: 'Screenshot anhängen – oder mit ⌘V einfügen oder hineinziehen',
    remove: 'Entfernen',
    enlarge: 'Vergrößern',
    close: 'Schließen (Esc)',
    alt: 'Screenshot',
    uploading: 'lädt …',
  },
  empty: 'Noch keine Aufgaben. Doppelklick auf die Fläche legt eine an.',
};

const startOfDay = (d: Date) => new Date(d.getFullYear(), d.getMonth(), d.getDate()).getTime();

export const stateLabel = (i: { state: CardState; need?: Need; queue?: Queue; idea?: Idea; question?: unknown; finishing?: boolean; prototypeEnd?: 'discarded' | 'built' }) =>
  i.prototypeEnd
    ? t.idea.ended[i.prototypeEnd]
    : i.finishing && (i.state === 'live' || i.state === 'done')
    ? i.state === 'done' ? t.finishingDone : t.finishing
    : i.idea
    ? i.idea.status === 'open' && i.idea.yourTurn && !i.idea.thinking
      ? t.idea.yourTurn
      : t.idea.status[i.idea.status]
    : i.queue
    ? 'checking' in i.queue
      ? t.queue.checking
      : 'cutting' in i.queue
        ? t.queue.cutting
        : t.queue.waiting
    : i.state === 'waiting' && i.need
      ? i.need === 'demo' && i.question
        ? t.demoWithQuestion
        : t.need[i.need]
      : t.state[i.state];

/** The owner's text for a refused request or a logged error code; the generic one for anything unknown. */
export const errorText = (code: string | undefined) => (code && Object.hasOwn(t.error, code) ? t.error[code as ErrorCode] : t.error.invalid);
