// Every UI string. German first; an English table follows the same shape.

import type { CardState, Need, Queue } from '../core/types';

export const t = {
  kind: { feature: 'Feature', bugfix: 'Bugfix', project: 'Projekt', workstream: 'Workstream' },
  state: {
    proposal: 'Vorschlag eines Agenten',
    planned: 'Geplant',
    working: 'Agent arbeitet',
    waiting: 'Wartet auf dich',
    approved: 'Freigegeben',
    inPr: 'Im PR',
    live: 'Live',
  } satisfies Record<CardState, string>,
  need: { demo: 'Demo bereit', question: 'Frage an dich', review: 'Bereit zur Abnahme' } satisfies Record<Need, string>,
  proposalMark: '✦ Vorschlag · ',
  progress: (live: number, all: number) => `${live} von ${all} live`,
  needsYou: 'brauchen dich',
  newCard: 'Neue Karte',
  keys: 'Ziehen: verschieben · ⌘ + Scrollen / Pinch: Zoom · 0: Übersicht · Doppelklick: neue Karte',
  close: 'Schließen (Esc)',
  planSheet: 'Projekt · Plan',
  fromPlan: 'Aus dem Plan-Dokument; geändert wird es dort:',
  titlePlaceholder: 'Worum geht es?',
  bodyPlaceholder: 'Beschreibung',
  delete: 'Löschen',
  deleted: (title: string) => `Karte „${title}“ gelöscht.`,
  undo: 'Rückgängig',
  offline: 'Keine Verbindung zum Server',
  start: 'Agent starten',
  stop: 'Anhalten',
  approve: 'Freigeben',
  accept: 'Übernehmen',
  dismiss: 'Verwerfen',
  send: 'Senden',
  compose: {
    working: 'Hinweis an den Agenten – er arbeitet weiter',
    question: 'Eigene Antwort',
    review: 'Feedback – der Agent arbeitet daran weiter',
  },
  questionFromWorker: 'Frage des Agenten',
  summary: 'Zusammenfassung des Agenten',
  proposal: 'Vorschlag',
  proposedBy: (title: string) => `Vorgeschlagen vom Agenten der Karte „${title}“.`,
  task: 'Auftrag',
  log: 'Verlauf',
  logEmpty: 'Noch nichts passiert.',
  author: { worker: 'Agent', owner: 'Du', project: 'Projekt-Agent', obeya: 'Obeya' },
  branch: 'Branch',
  started: (title: string) => `Agent arbeitet an „${title}“.`,
  answered: 'Antwort ist beim Agenten.',
  approved: 'Freigegeben.',
  accepted: 'Vorschlag übernommen und eingeplant.',
  dismissed: 'Vorschlag verworfen.',
  stopped: 'Agent angehalten.',
  queue: {
    checking: 'Koordinator prüft',
    waiting: 'In der Warteschlange',
    checkingLong: 'Der Koordinator prüft, ob die Karte mit laufender Arbeit kollidiert.',
    behind: (titles: string[]) => `Wartet auf ${titles.map((x) => `„${x}“`).join(', ')}.`,
    force: 'Trotzdem starten',
    dequeue: 'Aus der Warteschlange nehmen',
    forced: 'Gestartet, trotz Überschneidung.',
    dequeued: 'Aus der Warteschlange genommen.',
  },
  scope: 'Voraussichtlich betroffen',
  empty: 'Noch keine Karten. Doppelklick auf die Fläche legt eine an.',
};

export const stateLabel = (i: { state: CardState; need?: Need; queue?: Queue }) =>
  i.queue ? ('checking' in i.queue ? t.queue.checking : t.queue.waiting) : i.state === 'waiting' && i.need ? t.need[i.need] : t.state[i.state];
