// Every UI string. German first; an English table follows the same shape.

import type { CardState, ConfigProblemCode, ErrorCode, Idea, Need, Queue, RestartReason } from '../core/types';

export const t = {
  kind: { feature: 'Feature', bugfix: 'Bugfix', project: 'Projekt', workstream: 'Workstream', idea: 'Idee', prototype: 'Prototyp' },
  state: {
    idea: 'Idee',
    proposal: 'Vorschlag eines Agenten',
    planned: 'Geplant',
    working: 'Agent arbeitet',
    waiting: 'Wartet auf dich',
    approved: 'Freigegeben',
    inPr: 'Im PR',
    live: 'Live',
  } satisfies Record<CardState, string>,
  need: { demo: 'Demo bereit', question: 'Frage an dich', review: 'Bereit zur Abnahme' } satisfies Record<Need, string>,
  demoWithQuestion: 'Demo bereit, mit Frage',
  finishing: 'Live · Agent erledigt den Rest',
  finishingLong: 'Auf main. Der Agent erledigt noch, was nach dem Landen ansteht; danach endet seine Sitzung.',
  proposalMark: '✦ Vorschlag · ',
  progress: (live: number, all: number) => `${live} von ${all} live`,
  needsYou: 'brauchen dich',
  newCard: 'Neue Karte',
  keys: 'Ziehen: verschieben · ⌘ + Scrollen / Pinch: Zoom · 0: Übersicht · Doppelklick: neue Karte · K: Koordinator · A: Archiv · Leertaste halten: sprechen',
  close: 'Schließen (Esc)',
  planSheet: 'Projekt · Plan',
  plan: {
    read: 'Plandokument lesen',
    readAt: 'Im Plandokument lesen',
    back: 'Workstreams',
    loading: 'Plandokument wird geladen …',
    failed: 'Das Plandokument ließ sich nicht laden.',
  },
  archivedProject: 'Projekt · Archiv',
  fromIdea: 'Entstanden aus der Idee',
  decisions: 'Entscheidungen',
  noDecisions: 'Noch keine Entscheidungen.',
  decidedBy: { owner: 'du', project: 'Projekt-Agent für dich', koordinator: 'Koordinator für dich' },
  fromPlan: 'Aus dem Plan-Dokument; geändert wird es dort:',
  titlePlaceholder: 'Worum geht es?',
  bodyPlaceholder: 'Beschreibung',
  delete: 'Löschen',
  deleted: (title: string) => `Karte „${title}“ gelöscht.`,
  undo: 'Rückgängig',
  offline: 'Keine Verbindung zum Server',
  noCanvas: 'Obeya hat keine Leinwand. Beim Start ein Repository angeben.',
  repos: (n: number) => `${n} Repositories`,
  switchCanvas: 'Leinwand wechseln',
  start: 'Agent starten',
  stop: 'Anhalten',
  approve: 'Freigeben',
  accept: 'Übernehmen und starten',
  acceptOnly: 'Übernehmen',
  dismiss: 'Verwerfen',
  send: 'Senden',
  compose: {
    working: 'Hinweis an den Agenten – er arbeitet weiter',
    question: 'Eigene Antwort',
    review: 'Feedback – der Agent arbeitet daran weiter',
  },
  questionFromWorker: 'Frage des Agenten',
  ask: {
    question: 'Frage an dich',
    questions: 'Fragen an dich',
    several: 'Mehrere möglich',
    words: 'Eigene Antwort oder Anmerkung – optional',
    send: 'Antworten',
  },
  summary: 'Zusammenfassung des Agenten',
  proposal: 'Vorschlag',
  proposedBy: (title: string) => `Vorgeschlagen vom Agenten der Karte „${title}“.`,
  followUpOf: (title: string) => `Kommt von der Karte „${title}“.`,
  task: 'Auftrag',
  log: 'Verlauf',
  logEmpty: 'Noch nichts passiert.',
  lastFailure: (at: string) => `Zuletzt gescheitert (${at})`,
  author: { worker: 'Agent', owner: 'Du', project: 'Projekt-Agent', koordinator: 'Koordinator', obeya: 'Obeya', explorer: 'Explorations-Agent' },
  branch: 'Branch',
  started: (title: string) => `Agent arbeitet an „${title}“.`,
  answered: 'Antwort ist beim Agenten.',
  approved: 'Freigegeben.',
  accepted: 'Vorschlag übernommen und gestartet.',
  dismissed: 'Vorschlag verworfen.',
  stopped: 'Agent angehalten.',
  queue: {
    checking: 'Koordinator prüft',
    cutting: 'Koordinator teilt auf',
    cuttingLong: 'Der Koordinator schneidet die Karte in Pakete, die parallel laufen können. Sie ersetzen die Karte.',
    waiting: 'In der Warteschlange',
    checkingLong: 'Der Koordinator prüft, ob die Karte mit laufender Arbeit wahrscheinlich in Merge-Konflikte gerät.',
    behind: (titles: string[]) => `Wartet auf ${titles.map((x) => `„${x}“`).join(', ')}.`,
    force: 'Trotzdem starten',
    dequeue: 'Aus der Warteschlange nehmen',
    forced: 'Gestartet, trotz möglicher Merge-Konflikte.',
    dequeued: 'Aus der Warteschlange genommen.',
  },
  /** Why the server refused an action; `invalid` is also the text for anything unknown. */
  error: {
    unknownCard: 'Diese Karte gibt es nicht mehr.',
    project: 'Ein Projekt wird über seine Workstreams bearbeitet, nicht als Ganzes.',
    notPlanned: 'Nur eine geplante Karte kann gestartet werden.',
    queued: 'Die Karte liegt schon beim Koordinator.',
    notQueued: 'Die Karte wartet nicht in der Warteschlange.',
    notSplittable: 'Aufteilen lässt sich nur eine eigene, geplante Karte, die nicht beim Koordinator liegt.',
    noAgent: 'An dieser Karte arbeitet gerade kein Agent.',
    noQuestion: 'Die Karte hat keine offene Frage mehr.',
    notReady: 'Die Karte ist nicht bereit zur Abnahme.',
    notProposal: 'Die Karte ist kein Vorschlag mehr.',
    planCard: 'Die Karte kommt aus dem Plan-Dokument; geändert wird sie dort.',
    noWorkspace: 'Kein Workspace frei: Alle sind belegt oder es ist keiner eingerichtet.',
    dirtyWorkspaces: 'Kein Workspace frei: Jeder freie hat noch nicht committete Änderungen.',
    workspace: 'Der Workspace für den Agenten ließ sich nicht vorbereiten (git-Fehler).',
    emptyText: 'Bitte zuerst einen Text eingeben.',
    unknownPreference: 'Diese Präferenz gibt es nicht mehr.',
    imageType: 'Das ist kein Bild, das der Agent lesen kann (PNG, JPEG, GIF oder WebP).',
    imageTooLarge: 'Das Bild ist zu groß, auch verkleinert.',
    notDone: 'Archivieren lässt sich nur eine eigene Karte, die live ist.',
    notArchived: 'Die Karte liegt nicht mehr im Archiv.',
    notIdea: 'Die Karte ist keine Idee (mehr).',
    prototypeRunning: 'Für diese Idee läuft schon ein Prototyp.',
    landDirty: 'Nicht gelandet: Im Workspace liegen noch nicht committete Änderungen. Der Agent kümmert sich darum; danach landet die Arbeit ohne neue Freigabe.',
    landConflict: 'Nicht gelandet: Beim Rebase auf main gab es Konflikte. Der Agent löst sie; danach landet die Arbeit ohne neue Freigabe.',
    landEmpty: 'Nicht gelandet: Der Branch enthält keine Commits. Der Agent sieht nach; danach landet die Arbeit ohne neue Freigabe.',
    landCheckout: 'Nicht gelandet: Der Obeya-Checkout steht nicht auf main. Bitte dort auf main wechseln und erneut freigeben.',
    landMerge: 'Nicht gelandet: Der Obeya-Checkout hat lokale Änderungen an denselben Dateien. Bitte dort committen oder beiseitelegen und erneut freigeben.',
    land: 'Nicht gelandet: git-Fehler im Obeya-Checkout.',
    config: 'Nicht gespeichert: Die Konfiguration hat Fehler.',
    invalid: 'Das hat nicht geklappt. Der Server hat die Aktion abgelehnt.',
  } satisfies Record<ErrorCode, string>,
  offlineError: 'Der Server ist nicht erreichbar.',
  scope: 'Voraussichtlich betroffen',
  voice: {
    hold: 'Halten zum Sprechen (Leertaste)',
    koordinator: 'Koordinator',
    card: (title: string) => `Koordinator · Karte: ${title}`,
    idea: (title: string) => `Koordinator · Idee: ${title}`,
    project: (title: string) => `Koordinator · Projekt: ${title}`,
    noMic: 'Kein Mikrofon: der Browser hat den Zugriff nicht erlaubt.',
    notReady: 'Das Mikrofon war noch nicht bereit; bitte noch einmal.',
    flat: 'Das Mikrofon liefert keinen Ton.',
    failed: 'Das hat nicht geklappt; bitte noch einmal.',
    typePlaceholder: 'Dem Koordinator schreiben, z. B. „Neue Karte: …“',
    tooLate: 'Zu spät: das ist schon passiert.',
    attach: 'Screenshot für die nächste Sprachnachricht – oder mit ⌘V einfügen oder auf das Mikrofon ziehen',
  },
  pr: {
    title: (n: number) => `Pull Request #${n}`,
    conflict: 'Konflikt mit dem Zielbranch; der Agent rebased.',
    noChecks: 'Noch keine Checks.',
    opening: 'Der Agent öffnet den Pull Request.',
    short: (n: number, failed: number, conflict: boolean) =>
      [`PR #${n}`, failed ? `${failed} ${failed === 1 ? 'Check rot' : 'Checks rot'}` : '', conflict ? 'Konflikt' : ''].filter(Boolean).join(' · '),
  },
  demo: { question: 'Offene Frage', answerPlaceholder: 'Antwort an den Agenten', yourAnswer: 'Deine Antwort', shown: 'Gezeigt', notShown: 'Nicht gezeigt', findings: 'Auffälligkeiten', none: '–', kept: 'Die Demo bleibt hier abrufbar.',
    followUp: 'Als Karte anlegen',
    followedUp: (title: string) => `Karte „${title}“ angelegt`,
  },
  koordinator: {
    button: 'Koordinator',
    kind: 'Koordinator',
    title: 'Planung und Präferenzen',
    queue: 'Warteschlange',
    queueEmpty: 'Nichts wartet.',
    running: 'In Arbeit',
    runningEmpty: 'Gerade arbeitet kein Agent.',
    preferences: 'Deine Präferenzen',
    preferencesHint: 'Der Koordinator lernt sie aus deinen Antworten und Hinweisen; alle Agenten halten sich daran.',
    edit: 'Zum Bearbeiten klicken',
    remove: 'Entfernen',
    add: 'Hinzufügen',
    addPlaceholder: 'Neue Präferenz',
    undone: 'zurückgenommen',
    lookingUp: 'schlägt nach …',
  },
  config: {
    button: 'Konfiguration',
    kind: 'Obeya',
    title: 'Konfiguration',
    fromFile: 'Gespeichert in',
    fromArgs: (file: string) =>
      `Obeya läuft gerade mit den Repositories von der Kommandozeile. Speichern legt ${file} an; Obeya startet dann daraus, auch künftig, wenn es ohne Repositories gestartet wird.`,
    koordinator: 'Der Koordinator kennt sie auch: frag ihn danach oder sag ihm, was sich ändern soll.',
    canvas: (n: number) => `Leinwand ${n}`,
    name: 'Name',
    nameAuto: (name: string) => `automatisch: ${name}`,
    runs: 'läuft',
    fresh: 'neu',
    freshHint: 'Neue Kennung: Obeya zeigt hier eine neue, leere Leinwand.',
    gone: (names: string) => `Nicht mehr dabei: ${names}. Ihre Karten bleiben gespeichert und kommen mit der Leinwand zurück.`,
    path: 'Pfad zum Repository',
    home: 'Heimat',
    adapter: 'Adapter',
    adapterAuto: (picked?: string) => (picked ? `automatisch (${picked})` : 'automatisch'),
    worktrees: 'Agenten arbeiten in Worktrees',
    clonesMode: 'Agenten arbeiten in Klonen',
    clones: 'Klone anlegen',
    workspaces: 'Vorhandene Klone, einer pro Zeile',
    addRepo: '+ Repository',
    removeRepo: 'Repository entfernen',
    addCanvas: '+ Leinwand',
    removeCanvas: 'Leinwand entfernen',
    server: 'Server (von der Kommandozeile)',
    port: 'Port',
    dataDir: 'Daten',
    permissionMode: 'Rechte der Agenten',
    restarts: 'Startet bei neuem Code neu',
    yes: 'ja',
    no: 'nein (--dev)',
    save: 'Speichern und neu starten',
    saveOnly: 'Speichern',
    reset: 'Verwerfen',
    saved: 'Gespeichert. Obeya startet neu, sobald kein Agent mitten in einem Schritt ist; die Seite lädt dann von selbst neu.',
    savedOnly: 'Gespeichert. Gilt ab dem nächsten Start von Obeya.',
    json: 'Als JSON',
    loading: 'Konfiguration wird geladen …',
    problem: {
      noCanvas: 'Obeya braucht mindestens eine Leinwand.',
      noRepo: 'Eine Leinwand braucht mindestens ein Repository.',
      notRepo: 'Unter diesem Pfad liegt kein git-Repository.',
      unknownAdapter: 'Diesen Adapter gibt es nicht.',
      sameId: 'Gleiche Kennung wie eine andere Leinwand: bitte einen anderen Namen geben.',
      homeMissing: 'Das Repository, mit dem die Leinwand angelegt wurde, fehlt; es muss dabeibleiben.',
      notClone: 'Ein Klon in der Liste ist kein git-Repository.',
      invalid: 'Die Konfiguration ist fehlerhaft.',
    } satisfies Record<ConfigProblemCode, string>,
  },
  restart: {
    pill: (n: number) => (n === 1 ? 'Neustart wartet auf 1 Agenten' : `Neustart wartet auf ${n} Agenten`),
    until: (time: string) => `spätestens ${time}`,
    reason: {
      code: 'Auf main liegt neuer Code, mit dem Obeya neu startet.',
      config: 'Die Konfiguration wurde gespeichert; Obeya startet mit ihr neu.',
    } satisfies Record<RestartReason, string>,
    waits: 'Die Agenten wissen Bescheid und pausieren beim nächsten sicheren Punkt. Obeya wartet noch auf:',
    elsewhere: (n: number) => (n === 1 ? '1 Agent auf einer anderen Leinwand' : `${n} Agenten auf anderen Leinwänden`),
    deadline: (time: string) => `Um ${time} startet Obeya auf jeden Fall neu.`,
    now: 'Jetzt neu starten',
    nowRisk:
      'Ohne zu warten: Die Agenten werden mitten im Schritt unterbrochen. Was sie gerade laufen lassen (Tests, Builds, gestartete Server, eine Demo-Aufnahme), wird gestoppt. Nach dem Neustart machen sie in ihrer Sitzung weiter und erfahren davon, müssen Abgebrochenes aber neu anstoßen; eine halb fertige Änderung liegt bis dahin unfertig im Workspace.',
    going: 'Obeya startet neu …',
  },
  archive: {
    button: 'Archiv',
    kind: 'Archiv',
    title: 'Erledigte Karten und Projekte',
    hint: 'Zuletzt archivierte oben. Ein Klick öffnet die Karte.',
    empty: 'Noch nichts archiviert.',
    archive: 'Archivieren',
    archiveDone: (n: number) => (n === 1 ? '1 erledigte Karte archivieren' : `${n} erledigte Karten archivieren`),
    unarchive: 'Zurück auf die Leinwand',
    archived: (title: string) => `„${title}“ archiviert.`,
    archivedMany: (n: number) => (n === 1 ? '1 Karte archiviert.' : `${n} Karten archiviert.`),
    unarchived: (title: string) => `„${title}“ ist zurück auf der Leinwand.`,
    /** The heading over the cards archived on one day. */
    day: (d: Date, today = new Date()) => {
      const days = Math.round((startOfDay(today) - startOfDay(d)) / 86_400_000);
      if (days === 0) return 'Heute';
      if (days === 1) return 'Gestern';
      return d.toLocaleDateString('de-DE', { weekday: 'long', day: 'numeric', month: 'long', ...(d.getFullYear() === today.getFullYear() ? {} : { year: 'numeric' }) });
    },
    /** When an archived card went into the archive, on the unfolded card. */
    when: (d: Date) => {
      const day = t.archive.day(d);
      return `archiviert ${day === 'Heute' || day === 'Gestern' ? day.toLowerCase() : `am ${day}`}, ${d.toLocaleTimeString('de-DE', { hour: '2-digit', minute: '2-digit' })}`;
    },
    time: (d: Date) => `archiviert ${d.toLocaleTimeString('de-DE', { hour: '2-digit', minute: '2-digit' })}`,
    /** Over an archived project: its plan doc is gone, and the sheet shows it as it last stood. */
    projectGone: (d: Date) => `Das Plan-Dokument ist weg (${t.archive.when(d)}). So stand es zuletzt; kommt die Datei zurück, kehrt das Projekt an seinen Platz zurück.`,
    workstreams: (n: number) => (n === 1 ? '1 Workstream' : `${n} Workstreams`),
  },
  split: 'Aufteilen',
  idea: {
    status: { open: 'Idee', parked: 'Idee · geparkt', dropped: 'Idee · verworfen' } satisfies Record<Idea['status'], string>,
    yourTurn: 'Idee · du bist dran',
    brief: 'Stand der Idee',
    briefEmpty: 'Noch leer. Der Explorations-Agent hält hier fest, was das Gespräch ergibt: Ziel, Varianten, Entscheidungen, offene Fragen.',
    seed: 'Ausgangspunkt',
    talk: 'Gespräch',
    talkEmpty: 'Erzähl, worum es geht. Der Explorations-Agent liest Code und Pläne mit, fragt nach und zeigt Varianten.',
    thinking: 'denkt nach …',
    steps: (n: number) => `Verlauf: ${n} ${n === 1 ? 'Schritt' : 'Schritte'}`,
    compose: 'Frag nach, widersprich, entscheide – oder halte die Leertaste',
    build: 'So bauen',
    planDoc: 'Als Projekt planen',
    prototype: 'Prototyp bauen lassen',
    prototypePlaceholder: 'Was soll der Prototyp zeigen? (leer: die Idee, wie sie steht)',
    prototypeGo: 'Prototyp starten',
    park: 'Parken',
    drop: 'Verwerfen',
    built: 'Die Idee wird gebaut; der Stand der Idee ist ihr Auftrag.',
    planned: 'Eingeplant: Ein Agent schreibt das Plan-Doc.',
    parked: 'Idee geparkt.',
    dropped: 'Idee verworfen. Die Karte bleibt mit ihrem Stand liegen.',
    prototyped: 'Ein Agent baut einen Wegwerf-Prototyp.',
    prototypeDemo: 'Prototyp',
    prototypeKept: 'Der Prototyp landet nie; die Demo dient nur der Entscheidung.',
    reopen: 'Wer weiterredet, nimmt die Idee wieder auf.',
    makeIdea: 'Erst besprechen',
    prototypeOf: (title: string) => `Wegwerf-Prototyp für die Idee „${title}“. Er landet nie.`,
    discard: 'Prototyp verwerfen',
    discarded: 'Prototyp verworfen; die Demo bleibt bei der Idee.',
  },
  shots: {
    attach: 'Screenshot anhängen – oder mit ⌘V einfügen oder hineinziehen',
    remove: 'Entfernen',
    enlarge: 'Vergrößern',
    close: 'Schließen (Esc)',
    alt: 'Screenshot',
    uploading: 'lädt …',
  },
  empty: 'Noch keine Karten. Doppelklick auf die Fläche legt eine an.',
};

const startOfDay = (d: Date) => new Date(d.getFullYear(), d.getMonth(), d.getDate()).getTime();

export const stateLabel = (i: { state: CardState; need?: Need; queue?: Queue; idea?: Idea; question?: unknown; finishing?: boolean }) =>
  i.finishing && i.state === 'live'
    ? t.finishing
    : i.idea
    ? i.idea.status === 'open' && i.idea.yourTurn && !i.idea.thinking
      ? t.idea.yourTurn
      : t.idea.status[i.idea.status]
    : i.queue
    ? 'checking' in i.queue
      ? t.queue.checking
      : 'cutting' in i.queue
        ? t.queue.cutting
        : t.queue.waiting
    : i.state === 'waiting' && i.need
      ? i.need === 'demo' && i.question
        ? t.demoWithQuestion
        : t.need[i.need]
      : t.state[i.state];

/** The owner's text for a refused request or a logged error code; the generic one for anything unknown. */
export const errorText = (code: string | undefined) => (code && Object.hasOwn(t.error, code) ? t.error[code as ErrorCode] : t.error.invalid);
